[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://characterai-production-0b22.up.railway.app/api/:splat"
  status = 200
  force = true 